### PR TITLE
Compiles on FreeBSD 10.2

### PR DESCRIPTION
**Pull request by mslehto**
WIth these changes I can compile SEMS with FreeBSD 10.2.

### CODE REVIEW

**Comment by dunst0** [comment]
still having trouble with libevent2, installed from pkg

```
In file included from /usr/src/sems/core/AmB2BMedia.cpp:7:
/usr/src/sems/core/AmRtpReceiver.h:35:10: fatal error: 'event2/event.h' file not found
#include <event2/event.h>
         ^
1 error generated.
*** Error code 1

Stop.
make[2]: stopped in /usr/src/sems/build
*** Error code 1

Stop.
make[1]: stopped in /usr/src/sems/build
*** Error code 1

Stop.
make: stopped in /usr/src/sems/build
```

but

```
root@test:/usr/src/sems/build # cmake ..
[...]
-- Found libevent2 includes:	/usr/local/include/event2/event.h
-- Found libevent2 library: /usr/local/lib/libevent.so
[...]
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/src/sems/build
```

why aren't the paths used for linking that cmake discovers?

**Comment by dunst0** [comment]
Oh, you just fixed the Makefile, but what is with cmake?

**Comment by mslehto** [comment]
> could the changes in the cpp code possibly be put within #ifdefs?

Yes, of course

**Comment by dunst0** [comment]
what is missing for this pull request do get merged into master?

**Comment by dunst0** [comment]
having segmentation fault:

version 1.7-dev-40-g1f515de
FreeBSD 10.2-RELEASE

```
#0  0x0000000801bf6046 in sbrk () from /lib/libc.so.7
#1  0x0000000801bf64ef in sbrk () from /lib/libc.so.7
#2  0x0000000801c01b35 in free () from /lib/libc.so.7
#3  0x0000000800e0b89f in pthread_mutex_destroy () from /lib/libthr.so.3
#4  0x000000000053fc9a in ~trans_bucket (this=0x80283b310) at hash_table.h:51
#5  0x00000000005416a2 in ~hash_table (this=0x7c08e0) at hash_table.h:263
#6  0x0000000801c6c050 in __cxa_finalize () from /lib/libc.so.7
#7  0x0000000801c0d57c in exit () from /lib/libc.so.7
#8  0x0000000000456da6 in _start ()
#9  0x00000008007d2000 in ?? ()
#10 0x0000000000000000 in ?? ()
```

**Comment by mslehto** [comment]
@sanchi  commit 7746a5eae654f295cb4d6641110f145944a45cb0 does #ifdef to bring back original code

**Comment by mslehto** [comment]
Some debugging logged on issue #22

**Comment by mslehto** [comment]
Re-worked patch with *git push --force* (and lost @sanchi comments).
- *#if defined(IP_PKTINFO)* instead of *__linux* or *__bsd*
- no debug prints

**Comment by nwhitehorn** [comment]
This seems to be obsolete (I run sems on FreeBSD without issues).

**Comment by juha-h** [comment]
Reopen if still an issue.
